title: 我的个人博客
author: SSG284
description: Jekyll + GitHub Pages 博客
baseurl: ""
url: "https://ssg284.github.io"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
