name: Build and Deploy Blog
on:
  push:
    branches: [ main ]
permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby & Build Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - run: bundle exec jekyll build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
