name: 构建与部署博客
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
      - name: 配置Ruby环境
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Jekyll编译网站
        run: bundle install && bundle exec jekyll build
      - name: 上传静态页面产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      - name: 部署到GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
